version: '3'

networks:
  famnet:

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - ./.env
    ports:
      - "80:80"
    depends_on:
      - mongo
    networks:
      - famnet
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - famnet
  mongo:
    image: "mongo:latest"
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    command: [--auth]
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - famnet
    