# version: '3'
# services:
#   backend:
#     build:
#       context: .
#       dockerfile: ./backend/Dockerfile
#     ports:
#       - "80:80"
#     depends_on:
#       - mongo
#   frontend:
#     build:
#       context: .
#       dockerfile: ./frontend/Dockerfile
#     ports:
#       - "3000:3000"
#   mongo:
#     image: "mongo:latest"
#     ports:
#       - "27017:27017"
#     volumes:
#       - ./data:/data/db


version: '3'

networks:
  famnet:
    driver: bridge

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mongo
    networks:
      - famnet
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - famnet
  mongo:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
      MONGO_INITDB_DATABASE: "TodoList"
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - famnet
